extends Node
# holds master 'SONGS' array
var SONGS= [
	{"title": "Stateside",
	"artist": "PinkPantheress",
	"genre" : "Pop",
	"risk" : "Medium",
	"energy": 4
	},
	{"title": "Fate of Ophelia",
	"artist": "Taylor Swift",
	"genre" : "Pop",
	"risk" : "Low",
	"energy": 2
	},
	{"title": "Fame is A Gun",
	"artist": "Addison Rae",
	"genre" : "Pop",
	"risk" : "High",
	"energy": 5
	},
	{"title": "Tit for Tat",
	"artist": "Tate McRae",
	"genre" : "Pop",
	"risk" : "Low",
	"energy": 3
	},
	{"title": "Love Me Not",
	"artist": "Ravyn Lenae",
	"genre" : "Pop",
	"risk" : "Low",
	"energy": 1
	},
	{"title": "Good Luck, Babe!",
	"artist": "Chappel Roan",
	"genre" : "Pop",
	"risk" : "Medium",
	"energy": 3
	},
	{"title": "Kill Bill",
	"artist": "SZA",
	"genre" : "Pop",
	"risk" : "Medium",
	"energy": 2
	},
	{"title": "Into You",
	"artist": "Ariana Grande",
	"genre" : "Pop",
	"risk" : "Low",
	"energy": 4
	},
	{"title": "Vroom Vroom",
	"artist": "Charli XCX",
	"genre" : "Pop",
	"risk" : "High",
	"energy": 5
	},
	{"title": "Bad Liar",
	"artist": "Selena Gomez",
	"genre" : "Pop",
	"risk" : "High",
	"energy": 4
	},
	{"title": "Stereo Love",
	"artist": "Edward Maya",
	"genre" : "Euro",
	"risk" : "Low",
	"energy": 3
	},
	{"title": "Born Slippy",
	"artist": "Underworld",
	"genre" : "Euro",
	"risk" : "High",
	"energy": 4
	},
	{"title": "Better Off Alone",
	"artist": "Alice Deejay",
	"genre" : "Euro",
	"risk" : "Medium",
	"energy": 2
	},	
	{"title": "Sandstorm",
	"artist": "Darude",
	"genre" : "Euro",
	"risk" : "Low",
	"energy": 3
	},
	{"title": "We Like to Party!",
	"artist": "Vengaboys",
	"genre" : "Euro",
	"risk" : "High",
	"energy": 5
	},
	{"title": "Mr. Saxobeat",
	"artist": "Alexandra Stan",
	"genre" : "Euro",
	"risk" : "Medium",
	"energy": 4
	},
	{"title": "Children",
	"artist": "Robert Miles",
	"genre" : "Euro",
	"risk" : "Low",
	"energy": 2
	},
	{"title": "Barbie Girl",
	"artist": "Aqua",
	"genre" : "Euro",
	"risk" : "High",
	"energy": 4
	},
	{"title": "Be My Lover",
	"artist": "La Bouche",
	"genre" : "Euro",
	"risk" : "Low",
	"energy": 4
	},
	{"title": "Gypsy Woman",
	"artist": "Crystal Water",
	"genre" : "Euro",
	"risk" : "Low",
	"energy": 3
	},
	{"title": "Hypnotize",
	"artist": "The Notorious B.I.G",
	"genre" : "Hiphop",
	"risk" : "Low",
	"energy": 2
	},
	{"title": "1,2,3,4 (Sumpin' New)",
	"artist": "Coolio",
	"genre" : "Hiphop",
	"risk" : "Low",
	"energy": 3
	},
	{"title": "Back that Azz Up",
	"artist": "Lil Wayne",
	"genre" : "Hiphop",
	"risk" : "Medium",
	"energy": 5
	},
	{"title": "Mama Said Knock You Out",
	"artist": "LL Cool J",
	"genre" : "Hiphop",
	"risk" : "High",
	"energy": 4
	},
	{"title": "Hypnotize",
	"artist": "The Notorious B.I.G",
	"genre" : "Hiphop",
	"risk" : "Low",
	"energy": 2
	},
	{"title": "DNA",
	"artist": "Kenderick Lamar",
	"genre" : "Hiphop",
	"risk" : "Medium",
	"energy": 4
	},
	{"title": "POWER",
	"artist": "Kanye West",
	"genre" : "Hiphop",
	"risk" : "High",
	"energy": 5
	},
	{"title": "Ms. Jackson",
	"artist": "Outkast",
	"genre" : "Hiphop",
	"risk" : "Medium",
	"energy": 2
	},
	{"title": "Still D.R.E",
	"artist": "Dr.Dre",
	"genre" : "Hiphop",
	"risk" : "Medium",
	"energy": 3
	},
	{"title": "Drop It Like It's Hot",
	"artist": "Snoop Dogg",
	"genre" : "Hiphop",
	"risk" : "Low",
	"energy": 2
	},
	{"title": "No Scrubs",
	"artist": "TLC",
	"genre" : "RnB",
	"risk" : "Low",
	"energy": 3
	},
	{"title": "Breakin' Dishes",
	"artist": "Rihanna",
	"genre" : "RnB",
	"risk" : "High",
	"energy": 4
	},
	{"title": "Doo Wop (That Thing)",
	"artist": "Ms. Lauryn Hill",
	"genre" : "RnB",
	"risk" : "Low",
	"energy": 2
	},
	{"title": "Work It",
	"artist": "Missy Elliot",
	"genre" : "RnB",
	"risk" : "Low",
	"energy": 5
	},
	{"title": "Redbone",
	"artist": "Childish Gambino",
	"genre" : "RnB",
	"risk" : "Medium",
	"energy": 2
	},
	{"title": "Chanel",
	"artist": "Frank Ocean",
	"genre" : "RnB",
	"risk" : "High",
	"energy": 2
	},
	{"title": "MUTT",
	"artist": "Leon Thomas",
	"genre" : "RnB",
	"risk" : "Low",
	"energy": 2
	},
	{"title": "Bad Habit",
	"artist": "Steve Lacy",
	"genre" : "RnB",
	"risk" : "High",
	"energy": 2
	},
	{"title": "Party",
	"artist": "Beyonce",
	"genre" : "RnB",
	"risk" : "Low",
	"energy": 4
	},
	{"title": "The Days",
	"artist": "NOTION",
	"genre" : "EDM",
	"risk" : "Low",
	"energy": 2
	},
	{"title": "Von Dutch",
	"artist": "Charli XCX",
	"genre" : "EDM",
	"risk" : "Medium",
	"energy": 4
	},
	{"title": "212",
	"artist": "Azalea Banks",
	"genre" : "EDM",
	"risk" : "High",
	"energy": 5
	},
	{"title": "Heads Will Roll",
	"artist": "Yeah Yeah Yeahs",
	"genre" : "EDM",
	"risk" : "Low",
	"energy": 3
	},
	{"title": "Victory Lap",
	"artist": "Fred again..",
	"genre" : "EDM",
	"risk" : "Low",
	"energy": 4
	},
	{"title": "Latch",
	"artist": "Disclosure",
	"genre" : "EDM",
	"risk" : "Medium",
	"energy": 3
	},
	{"title": "Runaway (U&I)",
	"artist": "Falantis",
	"genre" : "EDM",
	"risk" : "Medium",
	"energy": 5
	},
	{"title": "Where You Are",
	"artist": "John Summit",
	"genre" : "EDM",
	"risk" : "Low",
	"energy": 4
	},
	{"title": "Midnight City",
	"artist": "M83",
	"genre" : "EDM",
	"risk" : "High",
	"energy": 5
	},
	{"title": "Clarity",
	"artist": "Zedd",
	"genre" : "EDM",
	"risk" : "Medium",
	"energy": 3
	}
		
]
func get_random_song() -> Dictionary:
	return SONGS.pickrandom()
